name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build & test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        configuration: [release, debug]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - os: macos-latest
            shape: circle
          - os: banana
          - os: banana
            animal: cat

    runs-on: windows-latest
    steps:
    - name: Test
      run: |
        echo "${{ matrix.os }} ${{matrix.configuration}} ${{ matrix.animal }} ${{ matrix.color }} ${{ matrix.shape }}"
