name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build & test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        configuration: [release, debug]
        include:
          - compiler: gcc
            os: windows-latest
            configuration: debug
          - compiler: clang
            os: windows-latest
            configuration: debug

    runs-on: windows-latest
    steps:
    - name: Test
      run: |
        echo "${{ matrix.os }} ${{matrix.configuration}} ${{ matrix.compiler }}"
